const Map<String, List<String>> trDialogs = {
  'Summary': ['Riassunto', 'Resumen', 'Zusammenfassung'],
  'What emerges, likely identities, gaps': ['Cosa emerge, identità probabili, lacune', 'Qué surge, identidades probables, lagunas', 'Was sich zeigt, wahrscheinliche Identitäten, Lücken'],
  'Review': ['Verifica', 'Verificación', 'Prüfung'],
  'Inconsistencies and likely false positives': ['Incongruenze e probabili falsi positivi', 'Incoherencias y probables falsos positivos', 'Widersprüche und wahrscheinliche Fehltreffer'],
  'What to look for now': ['Cosa cercare ora', 'Qué buscar ahora', 'Wonach jetzt suchen'],
  'Data to extend the search from': ['Dati da cui estendere la ricerca', 'Datos desde los que ampliar la búsqueda', 'Daten, von denen die Suche ausgeweitet wird'],
  'Draft report': ['Bozza di rapporto', 'Borrador de informe', 'Berichtsentwurf'],
  'Report in Markdown': ['Rapporto in Markdown', 'Informe en Markdown', 'Bericht in Markdown'],
  'Backend unreachable: {0}': ['Backend non raggiungibile: {0}', 'Backend no accesible: {0}', 'Backend nicht erreichbar: {0}'],
  'AI ANALYSIS': ['ANALISI AI', 'ANÁLISIS IA', 'KI-ANALYSE'],
  'Connector not configured: {0}.': ['Connettore non configurato: {0}.', 'Conector no configurado: {0}.', 'Connector nicht konfiguriert: {0}.'],
  'CONFIGURE': ['CONFIGURA', 'CONFIGURAR', 'KONFIGURIEREN'],
  '{0} · {1}  —  the investigation data is sent to this service': ['{0} · {1}  —  i dati dell\'indagine vengono inviati a questo servizio', '{0} · {1}  —  los datos de la investigación se envían a este servicio', '{0} · {1}  —  die Daten der Untersuchung werden an diesen Dienst gesendet'],
  'ask a question about the investigation…': ['fai una domanda sull\'indagine…', 'haz una pregunta sobre la investigación…', 'stelle eine Frage zur Untersuchung…'],
  'Ask': ['Chiedi', 'Preguntar', 'Fragen'],
  'Copy': ['Copia', 'Copiar', 'Kopieren'],
  'the model is analysing the graph…': ['il modello sta analizzando il grafo…', 'el modelo está analizando el grafo…', 'das Modell analysiert den Graphen…'],
  'pick an analysis or write a question': ['scegli un\'analisi o scrivi una domanda', 'elige un análisis o escribe una pregunta', 'wähle eine Analyse oder schreibe eine Frage'],
  'SUGGESTIONS': ['SUGGERIMENTI', 'SUGERENCIAS', 'VORSCHLÄGE'],
  'EXPAND': ['ESPANDI', 'EXPANDIR', 'ERWEITERN'],
  'private note…': ['nota privata…', 'nota privada…', 'private Notiz…'],
  'backend not found (set OSINT_BACKEND_DIR)': ['backend non trovato (imposta OSINT_BACKEND_DIR)', 'backend no encontrado (define OSINT_BACKEND_DIR)', 'Backend nicht gefunden (OSINT_BACKEND_DIR setzen)'],
  'backend failed to start: {0}': ['avvio backend fallito: {0}', 'error al iniciar el backend: {0}', 'Backend-Start fehlgeschlagen: {0}'],
  'backend started but not responding on {0}': ['backend avviato ma non risponde su {0}', 'backend iniciado pero no responde en {0}', 'Backend gestartet, antwortet aber nicht unter {0}'],
  'Edit node': ['Modifica nodo', 'Editar nodo', 'Knoten bearbeiten'],
  'New node': ['Nuovo nodo', 'Nuevo nodo', 'Neuer Knoten'],
  'TYPE': ['TIPO', 'TIPO', 'TYP'],
  'pick one or type your own': ['scegli o scrivi il tuo', 'elige uno o escribe el tuyo', 'wähle einen oder gib einen eigenen ein'],
  'VALUE': ['VALORE', 'VALOR', 'WERT'],
  'name, address, description…': ['nome, indirizzo, descrizione…', 'nombre, dirección, descripción…', 'Name, Adresse, Beschreibung…'],
  'A hand-made node is marked by a golden diamond. You can link, annotate, hide, edit or delete it.': ['Un nodo creato a mano si riconosce dal rombo dorato. Puoi collegarlo, annotarlo, nasconderlo, modificarlo o eliminarlo.', 'Un nodo creado a mano se reconoce por el rombo dorado. Puedes enlazarlo, anotarlo, ocultarlo, editarlo o eliminarlo.', 'Ein von Hand erstellter Knoten ist an der goldenen Raute erkennbar. Du kannst ihn verknüpfen, kommentieren, ausblenden, bearbeiten oder löschen.'],
  'Cancel': ['Annulla', 'Cancelar', 'Abbrechen'],
  'SAVE': ['SALVA', 'GUARDAR', 'SPEICHERN'],
  'CREATE': ['CREA', 'CREAR', 'ERSTELLEN'],
  'New bridge': ['Nuovo ponte', 'Nuevo puente', 'Neue Brücke'],
  'RELATION': ['RELAZIONE', 'RELACIÓN', 'BEZIEHUNG'],
  'for example: works for': ['per esempio: lavora per', 'por ejemplo: trabaja para', 'zum Beispiel: arbeitet für'],
  'NOTE (OPTIONAL)': ['NOTA (FACOLTATIVA)', 'NOTA (OPCIONAL)', 'NOTIZ (OPTIONAL)'],
  'why you link them': ['perché li colleghi', 'por qué los enlazas', 'warum du sie verknüpfst'],
  'CREATE BRIDGE': ['CREA PONTE', 'CREAR PUENTE', 'BRÜCKE ERSTELLEN'],
  'linked to': ['collegato a', 'vinculado a', 'verknüpft mit'],
  'same person': ['stessa persona', 'misma persona', 'gleiche Person'],
  'works for': ['lavora per', 'trabaja para', 'arbeitet für'],
  'owns': ['possiede', 'posee', 'besitzt'],
  'family member of': ['familiare di', 'familiar de', 'Familienmitglied von'],
  'contact of': ['contatto di', 'contacto de', 'Kontakt von'],
  'uses': ['usa', 'usa', 'nutzt'],
  'suspected link to': ['sospetto legato a', 'sospechoso vinculado a', 'Verdacht auf Verbindung zu'],
  'located in': ['si trova a', 'se encuentra en', 'befindet sich in'],
};
