const Map<String, List<String>> trMain = {
  'A name and at least one seed are required': ['Servono un nome e almeno un seed', 'Se necesitan un nombre y al menos una semilla', 'Name und mindestens ein Seed erforderlich'],
  'Error': ['Errore', 'Error', 'Fehler'],
  'Error: {0}': ['Errore: {0}', 'Error: {0}', 'Fehler: {0}'],
  'Error: {0} (is the backend running on {1}?)': ['Errore: {0} (backend avviato su {1}?)', 'Error: {0} (¿está el backend en marcha en {1}?)', 'Fehler: {0} (läuft das Backend auf {1}?)'],
  'Error, note: {0}': ['Errore nota: {0}', 'Error de nota: {0}', 'Fehler Notiz: {0}'],
  'Error, export: {0}': ['Errore export: {0}', 'Error de exportación: {0}', 'Fehler beim Export: {0}'],
  'Stop requested…': ['Interruzione richiesta…', 'Interrupción solicitada…', 'Abbruch angefordert…'],
  '↳ expanding from {0} · {1} (depth {2})': ['↳ espansione da {0} · {1} (profondità {2})', '↳ expansión desde {0} · {1} (profundidad {2})', '↳ Erweiterung von {0} · {1} (Tiefe {2})'],
  '+ node created: {0} · {1}': ['+ nodo creato: {0} · {1}', '+ nodo creado: {0} · {1}', '+ Knoten erstellt: {0} · {1}'],
  'Already existed: {0} · {1}': ['Esisteva già: {0} · {1}', 'Ya existía: {0} · {1}', 'Existierte bereits: {0} · {1}'],
  'The {0} nodes of the group are deleted along with their links. Data that came only from them is hidden (you can show it again). An update will not recreate them.': [
    'Vengono eliminati i {0} nodi del gruppo con i loro collegamenti. I dati che partivano solo da loro vengono nascosti (potrai rimostrarli). Un aggiornamento non li ricreerà.',
    'Se eliminan los {0} nodos del grupo con sus enlaces. Los datos que procedían solo de ellos se ocultan (podrás volver a mostrarlos). Una actualización no los recreará.',
    'Die {0} Knoten der Gruppe werden mit ihren Verbindungen gelöscht. Daten, die nur von ihnen stammten, werden ausgeblendet (du kannst sie wieder einblenden). Eine Aktualisierung erstellt sie nicht neu.'],
  'The bridges that connect it and its notes are deleted too. Data that came only from it is hidden (you can show it again).': [
    'Vengono eliminati anche i ponti che lo collegano e le sue note. I dati che partivano solo da lui vengono nascosti (potrai rimostrarli).',
    'También se eliminan los puentes que lo conectan y sus notas. Los datos que procedían solo de él se ocultan (podrás volver a mostrarlos).',
    'Auch die Brücken, die ihn verbinden, und seine Notizen werden gelöscht. Daten, die nur von ihm stammten, werden ausgeblendet (du kannst sie wieder einblenden).'],
  'The node and its links are deleted and an update will not recreate it. Data that came only from it is hidden (you can show it again).': [
    'Il nodo e i suoi collegamenti vengono eliminati e un aggiornamento non lo ricreerà. I dati che partivano solo da lui vengono nascosti (potrai rimostrarli).',
    'El nodo y sus enlaces se eliminan y una actualización no lo recreará. Los datos que procedían solo de él se ocultan (podrás volver a mostrarlos).',
    'Der Knoten und seine Verbindungen werden gelöscht, und eine Aktualisierung erstellt ihn nicht neu. Daten, die nur von ihm stammten, werden ausgeblendet (du kannst sie wieder einblenden).'],
  'Delete group «{0}»?': ['Eliminare il gruppo «{0}»?', '¿Eliminar el grupo «{0}»?', 'Gruppe «{0}» löschen?'],
  'Delete node «{0}»?': ['Eliminare il nodo «{0}»?', '¿Eliminar el nodo «{0}»?', 'Knoten «{0}» löschen?'],
  'Delete search «{0}»?': ['Eliminare la ricerca «{0}»?', '¿Eliminar la búsqueda «{0}»?', 'Suche «{0}» löschen?'],
  '✕ deleted {0} nodes': ['✕ eliminati {0} nodi', '✕ {0} nodos eliminados', '✕ {0} Knoten gelöscht'],
  '✕ deleted {0} nodes, hid {1} that depended on them': ['✕ eliminati {0} nodi, nascosti {1} che ne dipendevano', '✕ {0} nodos eliminados, {1} dependientes ocultados', '✕ {0} Knoten gelöscht, {1} davon abhängige ausgeblendet'],
  'A group cannot be linked: turn off «group» to pick a single node': ['Un gruppo non si può collegare: spegni «raggruppa» per scegliere un nodo singolo', 'Un grupo no se puede enlazar: desactiva «agrupar» para elegir un nodo individual', 'Eine Gruppe kann nicht verbunden werden: «gruppieren» ausschalten, um einen einzelnen Knoten zu wählen'],
  '+ bridge: {0} —{1}→ {2}': ['+ ponte: {0} —{1}→ {2}', '+ puente: {0} —{1}→ {2}', '+ Brücke: {0} —{1}→ {2}'],
  'Give the map a name': ['Dai un nome alla mappa', 'Ponle un nombre al mapa', 'Gib der Karte einen Namen'],
  'Graph, evidence, images and cached results of this search are deleted. This cannot be undone.': [
    'Grafo, evidenze, immagini e risultati in cache di questa ricerca vengono cancellati. Non si può annullare.',
    'El grafo, las evidencias, las imágenes y los resultados en caché de esta búsqueda se eliminan. No se puede deshacer.',
    'Graph, Belege, Bilder und zwischengespeicherte Ergebnisse dieser Suche werden gelöscht. Das kann nicht rückgängig gemacht werden.'],
  'Cancel': ['Annulla', 'Cancelar', 'Abbrechen'],
  'Delete': ['Elimina', 'Eliminar', 'Löschen'],
  'Loaded «{0}» (#{1})': ['Caricata «{0}» (#{1})', 'Cargada «{0}» (#{1})', '«{0}» geladen (#{1})'],
  '↻ updating «{0}»': ['↻ aggiornamento di «{0}»', '↻ actualizando «{0}»', '↻ Aktualisierung von «{0}»'],
  'Exported: {0}': ['Esportato: {0}', 'Exportado: {0}', 'Exportiert: {0}'],
  '{0} · {1} · {2} results': ['{0} · {1} · {2} risultati', '{0} · {1} · {2} resultados', '{0} · {1} · {2} Ergebnisse'],
  'Stopped': ['Interrotta', 'Interrumpida', 'Abgebrochen'],
  'Stopped · partial results saved': ['Interrotta · risultati parziali salvati', 'Interrumpida · resultados parciales guardados', 'Abgebrochen · Teilergebnisse gespeichert'],
  'Completed': ['Completato', 'Completado', 'Abgeschlossen'],
  'Completed · +{0} new items': ['Completato · +{0} nuovi dati', 'Completado · +{0} datos nuevos', 'Abgeschlossen · +{0} neue Daten'],
  '// no graph\n// start a search': ['// nessun grafo\n// avvia una ricerca', '// ningún grafo\n// inicia una búsqueda', '// kein Graph\n// Suche starten'],
  'WITH HIDDEN': ['CON I NASCOSTI', 'CON LOS OCULTOS', 'MIT AUSGEBLENDETEN'],
  'WITHOUT HIDDEN': ['SENZA I NASCOSTI', 'SIN LOS OCULTOS', 'OHNE AUSGEBLENDETE'],
  'CLEAN': ['PULITA', 'LIMPIA', 'SAUBER'],
  'Without the hidden nodes': ['Senza i nodi nascosti', 'Sin los nodos ocultos', 'Ohne die ausgeblendeten Knoten'],
  'FULL': ['COMPLETA', 'COMPLETA', 'VOLLSTÄNDIG'],
  'With the hidden nodes, faded': ['Con i nodi nascosti, sbiaditi', 'Con los nodos ocultos, atenuados', 'Mit den ausgeblendeten Knoten, abgeblendet'],
  'SIDE BY SIDE': ['AFFIANCATE', 'LADO A LADO', 'NEBENEINANDER'],
  'The two views next to each other': ["Le due viste una accanto all'altra", 'Las dos vistas una junto a la otra', 'Die beiden Ansichten nebeneinander'],
  '{0} hidden': ['{0} nascosti', '{0} ocultos', '{0} ausgeblendet'],
  'SHOW ALL': ['MOSTRA TUTTI', 'MOSTRAR TODOS', 'ALLE ANZEIGEN'],
  'BRIDGE · click the start node': ['PONTE · clicca il nodo di partenza', 'PUENTE · haz clic en el nodo de origen', 'BRÜCKE · Startknoten anklicken'],
  'BRIDGE · from «{0}» click the destination': ['PONTE · da «{0}» clicca la destinazione', 'PUENTE · desde «{0}» haz clic en el destino', 'BRÜCKE · von «{0}», Zielknoten anklicken'],
  'CANCEL (Esc)': ['ANNULLA (Esc)', 'CANCELAR (Esc)', 'ABBRECHEN (Esc)'],
  'search the graph (⌘/Ctrl+F)': ['cerca nel grafo (⌘/Ctrl+F)', 'buscar en el grafo (⌘/Ctrl+F)', 'im Graph suchen (⌘/Strg+F)'],
  '{0} found': ['{0} trovati', '{0} encontrados', '{0} gefunden'],
  'Hide the nodes found': ['Nascondi i nodi trovati', 'Ocultar los nodos encontrados', 'Gefundene Knoten ausblenden'],
  'Hide all the others (only what you found stays)': ['Nascondi tutti gli altri (resta solo ciò che hai trovato)', 'Ocultar todos los demás (solo queda lo encontrado)', 'Alle anderen ausblenden (nur das Gefundene bleibt)'],
  'Open panel (⌘/Ctrl+B)': ['Apri pannello (⌘/Ctrl+B)', 'Abrir panel (⌘/Ctrl+B)', 'Panel öffnen (⌘/Strg+B)'],
  'Collapse panel (⌘/Ctrl+B)': ['Riduci pannello (⌘/Ctrl+B)', 'Contraer panel (⌘/Ctrl+B)', 'Panel einklappen (⌘/Strg+B)'],
  'New search (⌘/Ctrl+N)': ['Nuova ricerca (⌘/Ctrl+N)', 'Nueva búsqueda (⌘/Ctrl+N)', 'Neue Suche (⌘/Strg+N)'],
  'AI analysis': ['Analisi AI', 'Análisis de IA', 'KI-Analyse'],
  'Settings': ['Impostazioni', 'Ajustes', 'Einstellungen'],
  'Export': ['Esporta', 'Exportar', 'Exportieren'],
  'Obsidian folder': ['Cartella Obsidian', 'Carpeta de Obsidian', 'Obsidian-Ordner'],
  'Previous searches': ['Ricerche precedenti', 'Búsquedas anteriores', 'Frühere Suchen'],
  'search by name': ['cerca per nome', 'buscar por nombre', 'nach Name suchen'],
  '#{0} · {1} entities · upd. {2}': ['#{0} · {1} entità · agg. {2}', '#{0} · {1} entidades · act. {2}', '#{0} · {1} Entitäten · akt. {2}'],
  'no results': ['nessun risultato', 'sin resultados', 'keine Ergebnisse'],
  'Search': ['Ricerca', 'Búsqueda', 'Suche'],
  'name': ['nome', 'nombre', 'Name'],
  'purpose (optional)': ['motivazione (facoltativa)', 'motivo (opcional)', 'Zweck (optional)'],
  'Seed': ['Seed', 'Semilla', 'Seed'],
  'value': ['valore', 'valor', 'Wert'],
  'Add seed': ['Aggiungi seed', 'Añadir semilla', 'Seed hinzufügen'],
  'Depth · {0}': ['Profondità · {0}', 'Profundidad · {0}', 'Tiefe · {0}'],
  'STOPPING…': ['INTERRUZIONE…', 'INTERRUMPIENDO…', 'WIRD ABGEBROCHEN…'],
  'STOP': ['FERMA', 'DETENER', 'STOPP'],
  'START': ['AVVIA', 'INICIAR', 'START'],
  'or create an empty map to build by hand': ['oppure crea una mappa vuota da costruire a mano', 'o crea un mapa vacío para construirlo a mano', 'oder eine leere Karte zum manuellen Aufbau erstellen'],
  'UPDATE': ['AGGIORNA', 'ACTUALIZAR', 'AKTUALISIEREN'],
  'map without seeds: add one to be able to update it': ['mappa senza seed: aggiungine uno per poterla aggiornare', 'mapa sin semillas: añade una para poder actualizarlo', 'Karte ohne Seeds: füge einen hinzu, um sie zu aktualisieren'],
  'last update {0}': ['ultimo aggiornamento {0}', 'última actualización {0}', 'letzte Aktualisierung {0}'],
  'last update {0} · {1} runs': ['ultimo aggiornamento {0} · {1} esecuzioni', 'última actualización {0} · {1} ejecuciones', 'letzte Aktualisierung {0} · {1} Ausführungen'],
  'starting backend…': ['avvio backend…', 'iniciando backend…', 'Backend wird gestartet…'],
  'retry': ['riprova', 'reintentar', 'erneut versuchen'],
  '{0} nodes · {1} edges': ['{0} nodi · {1} archi', '{0} nodos · {1} aristas', '{0} Knoten · {1} Kanten'],
  '● {0} new ✕': ['● {0} nuovi ✕', '● {0} nuevos ✕', '● {0} neu ✕'],
  'group': ['raggruppa', 'agrupar', 'gruppieren'],
  'To review': ['Da verificare', 'Por verificar', 'Zu prüfen'],
  'Favorites': ['Preferiti', 'Favoritos', 'Favoriten'],
  'Look for more data starting from this one': ['Cerca altri dati a partire da questo', 'Buscar más datos a partir de este', 'Weitere Daten ausgehend von diesem suchen'],
  'Only this item': ['Solo questo dato', 'Solo este dato', 'Nur dieses Datum'],
  'Up to depth 1': ['Fino a profondità 1', 'Hasta profundidad 1', 'Bis Tiefe 1'],
  'Up to depth 2': ['Fino a profondità 2', 'Hasta profundidad 2', 'Bis Tiefe 2'],
  'EXPAND · {0} «{1}»': ['ESPANDI · {0} «{1}»', 'EXPANDIR · {0} «{1}»', 'ERWEITERN · {0} «{1}»'],
  'SEARCH ON': ['CERCA SU', 'BUSCAR EN', 'SUCHEN BEI'],
  'Confirm': ['Conferma', 'Confirmar', 'Bestätigen'],
  'Discard': ['Scarta', 'Descartar', 'Verwerfen'],
  'SHOW': ['MOSTRA', 'MOSTRAR', 'ANZEIGEN'],
  'HIDE': ['NASCONDI', 'OCULTAR', 'AUSBLENDEN'],
  'LINK TO…': ['COLLEGA A…', 'ENLAZAR CON…', 'VERBINDEN MIT…'],
  'EDIT': ['MODIFICA', 'EDITAR', 'BEARBEITEN'],
  'DELETE': ['ELIMINA', 'ELIMINAR', 'LÖSCHEN'],
  'Remove from favorites': ['Rimuovi dai preferiti', 'Quitar de favoritos', 'Aus Favoriten entfernen'],
  'Add to favorites': ['Aggiungi ai preferiti', 'Añadir a favoritos', 'Zu Favoriten hinzufügen'],
  'Delete this bridge': ['Elimina questo ponte', 'Eliminar este puente', 'Diese Brücke löschen'],
};
