const Map<String, List<String>> trReport = {
  'The logo is larger than 1 MB': ['Il logo supera 1 MB', 'El logotipo supera 1 MB', 'Das Logo ist größer als 1 MB'],
  'The logo must be a PNG or JPEG image': ['Il logo deve essere un\'immagine PNG o JPEG', 'El logotipo debe ser una imagen PNG o JPEG', 'Das Logo muss ein PNG- oder JPEG-Bild sein'],
  'Cannot read the file': ['Impossibile leggere il file', 'No se puede leer el archivo', 'Die Datei kann nicht gelesen werden'],
  'Relations': ['Relazioni', 'Relaciones', 'Beziehungen'],
  'Suspected links': ['Collegamenti sospetti', 'Vínculos sospechosos', 'Vermutete Verbindungen'],
  'Proofs': ['Prove', 'Pruebas', 'Belege'],
  'Custom report': ['Report personalizzato', 'Informe personalizado', 'Benutzerdefinierter Bericht'],
  'Format': ['Formato', 'Formato', 'Format'],
  'HTML (standalone)': ['HTML (file singolo)', 'HTML (archivo único)', 'HTML (einzelne Datei)'],
  'Sections': ['Sezioni', 'Secciones', 'Abschnitte'],
  'Text': ['Testo', 'Texto', 'Text'],
  'Title': ['Titolo', 'Título', 'Titel'],
  'Header': ['Intestazione', 'Encabezado', 'Kopfzeile'],
  'Footer': ['Piè di pagina', 'Pie de página', 'Fußzeile'],
  'Logo': ['Logo', 'Logotipo', 'Logo'],
  'Path of a PNG or JPEG file (max 1 MB)': ['Percorso di un file PNG o JPEG (max 1 MB)', 'Ruta de un archivo PNG o JPEG (máx. 1 MB)', 'Pfad einer PNG- oder JPEG-Datei (max. 1 MB)'],
  'Clear': ['Rimuovi', 'Quitar', 'Entfernen'],
  'Include hidden items': ['Includi gli elementi nascosti', 'Incluir elementos ocultos', 'Ausgeblendete Elemente einbeziehen'],
  'Report language': ['Lingua del report', 'Idioma del informe', 'Sprache des Berichts'],
  'App language': ['Lingua dell\'app', 'Idioma de la aplicación', 'App-Sprache'],
  'Create': ['Crea', 'Crear', 'Erstellen'],
};
