// Translations for settings_dialog.dart: 'English source': [it, es, de].
const Map<String, List<String>> trSettings = {
  'Could not read settings: {0}': ['Impossibile leggere le impostazioni: {0}', 'No se pudieron leer los ajustes: {0}', 'Einstellungen konnten nicht gelesen werden: {0}'],
  'Settings saved': ['Impostazioni salvate', 'Ajustes guardados', 'Einstellungen gespeichert'],
  'SETTINGS': ['IMPOSTAZIONI', 'AJUSTES', 'EINSTELLUNGEN'],
  'General': ['Generale', 'General', 'Allgemein'],
  'Sources': ['Fonti', 'Fuentes', 'Quellen'],
  'API keys': ['Chiavi API', 'Claves API', 'API-Schlüssel'],
  'Data': ['Dati', 'Datos', 'Daten'],
  '{0} unsaved changes': ['{0} modifiche non salvate', '{0} cambios sin guardar', '{0} nicht gespeicherte Änderungen'],
  'Close': ['Chiudi', 'Cerrar', 'Schließen'],
  'SAVE': ['SALVA', 'GUARDAR', 'SPEICHERN'],
  'will be removed': ['verrà rimossa', 'se eliminará', 'wird entfernt'],
  'not set': ['non impostata', 'sin configurar', 'nicht gesetzt'],
  'set {0}': ['impostata {0}', 'configurada {0}', 'gesetzt {0}'],
  'remove': ['rimuovi', 'quitar', 'entfernen'],
  'paste the key': ['incolla la chiave', 'pega la clave', 'Schlüssel einfügen'],
  'paste to replace it': ['incolla per sostituirla', 'pega para reemplazarla', 'zum Ersetzen einfügen'],
  'New searches': ['Nuove ricerche', 'Nuevas búsquedas', 'Neue Suchen'],
  'Default depth': ['Profondità predefinita', 'Profundidad predeterminada', 'Standardtiefe'],
  'How many steps to follow the data found (0-4).': ['Quanti passi seguire i dati trovati (0-4).', 'Cuántos pasos seguir los datos encontrados (0-4).', 'Wie viele Schritte den gefundenen Daten gefolgt wird (0-4).'],
  'Entity limit per search': ['Limite di entità per ricerca', 'Límite de entidades por búsqueda', 'Entitätslimit pro Suche'],
  'The search stops following new data beyond this number.': ['La ricerca smette di seguire nuovi dati oltre questo numero.', 'La búsqueda deja de seguir nuevos datos al superar este número.', 'Die Suche verfolgt über diese Zahl hinaus keine neuen Daten.'],
  'Data handling': ['Gestione dei dati', 'Gestión de datos', 'Datenverarbeitung'],
  'Passive sources only': ['Solo fonti passive', 'Solo fuentes pasivas', 'Nur passive Quellen'],
  'Do not contact the target\'s servers: skips website, TLS port and DNS name guessing. Other sources stay active.': ['Non contattare i server del bersaglio: salta sito web, porta TLS e prove di nomi DNS. Le altre fonti restano attive.', 'No contactar los servidores del objetivo: omite el sitio web, el puerto TLS y la prueba de nombres DNS. Las demás fuentes siguen activas.', 'Die Server des Ziels nicht kontaktieren: überspringt Website, TLS-Port und DNS-Namensraten. Die übrigen Quellen bleiben aktiv.'],
  'Download profile images': ['Scarica le immagini profilo', 'Descargar imágenes de perfil', 'Profilbilder herunterladen'],
  'Used to compare photos across profiles. When off, no images are downloaded or saved.': ['Serve a confrontare le foto tra profili. Disattivandolo non vengono scaricate né salvate immagini.', 'Sirve para comparar fotos entre perfiles. Si se desactiva, no se descargan ni se guardan imágenes.', 'Dient zum Vergleich von Fotos zwischen Profilen. Ist es aus, werden keine Bilder heruntergeladen oder gespeichert.'],
  'Cache validity': ['Validità della cache', 'Validez de la caché', 'Cache-Gültigkeit'],
  'For how many hours to reuse a result already obtained (0 = always repeat the requests).': ['Per quante ore riusare un risultato già ottenuto (0 = rifai sempre le richieste).', 'Durante cuántas horas reutilizar un resultado ya obtenido (0 = repetir siempre las solicitudes).', 'Wie viele Stunden ein bereits erhaltenes Ergebnis wiederverwendet wird (0 = Anfragen immer wiederholen).'],
  'hours': ['ore', 'horas', 'Std.'],
  'Domains not to track': ['Domini da non tracciare', 'Dominios que no se rastrean', 'Nicht zu verfolgende Domains'],
  'Public mail providers and the like (gmail.com, outlook.com…): their addresses are searched, but the domain is not analysed. A domain chosen as seed is always searched.': ['Provider di posta pubblici e simili (gmail.com, outlook.com…): i loro indirizzi vengono cercati, ma il dominio non viene analizzato. Un dominio scelto come seed viene sempre cercato.', 'Proveedores de correo públicos y similares (gmail.com, outlook.com…): se buscan sus direcciones, pero no se analiza el dominio. Un dominio elegido como semilla siempre se busca.', 'Öffentliche Mailanbieter und Ähnliche (gmail.com, outlook.com…): Ihre Adressen werden gesucht, die Domain wird aber nicht analysiert. Eine als Seed gewählte Domain wird immer gesucht.'],
  'Group nodes from': ['Raggruppa nodi da', 'Agrupar nodos desde', 'Knoten gruppieren ab'],
  'Minimum number of similar nodes the graph merges into one group.': ['Numero minimo di nodi simili che il grafo unisce in un gruppo.', 'Número mínimo de nodos similares que el grafo une en un grupo.', 'Mindestanzahl ähnlicher Knoten, die der Graph zu einer Gruppe zusammenfasst.'],
  'Network': ['Rete', 'Red', 'Netzwerk'],
  'Parallel requests': ['Richieste in parallelo', 'Solicitudes en paralelo', 'Parallele Anfragen'],
  'Higher is faster but makes it easier for sites to block you.': ['Più alto è più veloce ma più facile essere bloccati dai siti.', 'Más alto es más rápido, pero es más fácil que los sitios te bloqueen.', 'Höher ist schneller, aber die Seiten sperren dich leichter.'],
  'Request timeout': ['Timeout richieste', 'Tiempo de espera de solicitudes', 'Anfrage-Timeout'],
  'Maximum wait for a response.': ['Attesa massima per una risposta.', 'Espera máxima de una respuesta.', 'Maximale Wartezeit auf eine Antwort.'],
  'sec': ['sec', 's', 'Sek.'],
  'Identity sent to the sites queried.': ['Identità inviata ai siti interrogati.', 'Identidad enviada a los sitios consultados.', 'An die abgefragten Seiten gesendete Kennung.'],
  'For example socks5://127.0.0.1:9050 (Tor) or http://host:port. Applies to web sources and Maigret; DNS queries do not go through the proxy.': ['Per esempio socks5://127.0.0.1:9050 (Tor) o http://host:porta. Vale per le fonti web e per Maigret; le query DNS non passano dal proxy.', 'Por ejemplo socks5://127.0.0.1:9050 (Tor) o http://host:puerto. Vale para las fuentes web y para Maigret; las consultas DNS no pasan por el proxy.', 'Zum Beispiel socks5://127.0.0.1:9050 (Tor) oder http://host:port. Gilt für Webquellen und Maigret; DNS-Abfragen laufen nicht über den Proxy.'],
  'empty = direct connection': ['vuoto = connessione diretta', 'vacío = conexión directa', 'leer = direkte Verbindung'],
  'Social media search': ['Ricerca sui social', 'Búsqueda en redes sociales', 'Suche in sozialen Netzwerken'],
  'From an email, look up the username': ['Da un\'email, cerca lo username', 'De un correo, buscar el nombre de usuario', 'Aus einer E-Mail den Benutzernamen suchen'],
  'Follows the part before the @ (if it looks personal, for example john.smith) and checks hundreds of sites and social networks with Maigret.': ['Segue la parte prima della @ (se sembra personale, per esempio mario.rossi) e controlla centinaia di siti e social con Maigret.', 'Sigue la parte anterior a la @ (si parece personal, por ejemplo mario.rossi) y comprueba cientos de sitios y redes sociales con Maigret.', 'Verfolgt den Teil vor dem @ (wenn er persönlich wirkt, z. B. mario.rossi) und prüft mit Maigret Hunderte von Seiten und sozialen Netzwerken.'],
  'From a name, try likely usernames': ['Da un nome, prova gli username probabili', 'De un nombre, probar los nombres de usuario probables', 'Aus einem Namen wahrscheinliche Benutzernamen testen'],
  'For “Mario Rossi” it tries mariorossi, mario.rossi, mrossi… Gives many false positives and each attempt takes about a minute.': ['Per «Mario Rossi» prova mariorossi, mario.rossi, mrossi… Dà molti falsi positivi e ogni tentativo richiede circa un minuto.', 'Para «Mario Rossi» prueba mariorossi, mario.rossi, mrossi… Da muchos falsos positivos y cada intento tarda aproximadamente un minuto.', 'Für „Mario Rossi“ werden mariorossi, mario.rossi, mrossi… probiert. Liefert viele Fehltreffer, und jeder Versuch dauert etwa eine Minute.'],
  'Username scan (Maigret)': ['Scansione username (Maigret)', 'Escaneo de nombres de usuario (Maigret)', 'Benutzernamen-Scan (Maigret)'],
  'Sites checked': ['Siti controllati', 'Sitios comprobados', 'Geprüfte Seiten'],
  'More sites = more results and more time.': ['Più siti = più risultati e più tempo.', 'Más sitios = más resultados y más tiempo.', 'Mehr Seiten = mehr Ergebnisse und mehr Zeit.'],
  'Timeout per site': ['Timeout per sito', 'Tiempo de espera por sitio', 'Timeout pro Seite'],
  'search source or type': ['cerca fonte o tipo', 'buscar fuente o tipo', 'Quelle oder Typ suchen'],
  '{0} active of {1}': ['{0} attive su {1}', '{0} activas de {1}', '{0} von {1} aktiv'],
  'enable all': ['abilita tutte', 'activar todas', 'alle aktivieren'],
  'contacts the target': ['contatta il bersaglio', 'contacta con el objetivo', 'kontaktiert das Ziel'],
  'requires key': ['richiede chiave', 'requiere clave', 'benötigt Schlüssel'],
  'TEST': ['PROVA', 'PROBAR', 'TESTEN'],
  'Here you connect your accounts to the platforms\' official APIs: searches are made on your behalf, within the limits and terms of the service. Facebook, Instagram and LinkedIn do not offer an API to search for people and forbid automated access with an account, so for those use the SEARCH ON buttons in the detail panel: they open the search in your browser, where you are already signed in.': ['Qui colleghi i tuoi account alle API ufficiali delle piattaforme: le ricerche vengono fatte a nome tuo, entro i limiti e i termini del servizio. Facebook, Instagram e LinkedIn non offrono un\'API per cercare persone e vietano l\'accesso automatico con un account, quindi per quelli usa i pulsanti CERCA SU del pannello dettaglio: aprono la ricerca nel tuo browser, dove sei già collegato.', 'Aquí conectas tus cuentas a las API oficiales de las plataformas: las búsquedas se hacen en tu nombre, dentro de los límites y los términos del servicio. Facebook, Instagram y LinkedIn no ofrecen una API para buscar personas y prohíben el acceso automático con una cuenta, así que para ellos usa los botones BUSCAR EN del panel de detalle: abren la búsqueda en tu navegador, donde ya has iniciado sesión.', 'Hier verbindest du deine Konten mit den offiziellen APIs der Plattformen: Die Suchen laufen in deinem Namen, im Rahmen der Limits und Nutzungsbedingungen des Dienstes. Facebook, Instagram und LinkedIn bieten keine API zur Personensuche und verbieten den automatisierten Zugriff mit einem Konto. Nutze dafür die Schaltflächen SUCHEN BEI im Detailbereich: Sie öffnen die Suche in deinem Browser, in dem du bereits angemeldet bist.'],
  'Credentials stay on your computer, in the local database, unencrypted.': ['Le credenziali restano sul tuo computer, nel database locale, non cifrate.', 'Las credenciales se quedan en tu ordenador, en la base de datos local, sin cifrar.', 'Die Zugangsdaten bleiben auf deinem Computer in der lokalen Datenbank, unverschlüsselt.'],
  'Connected accounts': ['Account collegati', 'Cuentas conectadas', 'Verbundene Konten'],
  'Personal token with no permissions: raises the limit from 60 to 5000 requests an hour.': ['Token personale senza permessi: porta il limite da 60 a 5000 richieste l\'ora.', 'Token personal sin permisos: sube el límite de 60 a 5000 solicitudes por hora.', 'Persönliches Token ohne Berechtigungen: erhöht das Limit von 60 auf 5000 Anfragen pro Stunde.'],
  'Create a “script” app at reddit.com/prefs/apps. Profile, account age, karma and communities where it is active.': ['Crea un\'app «script» su reddit.com/prefs/apps. Profilo, anzianità, karma e community in cui è attivo.', 'Crea una app «script» en reddit.com/prefs/apps. Perfil, antigüedad, karma y comunidades en las que está activo.', 'Erstelle unter reddit.com/prefs/apps eine „script“-App. Profil, Kontoalter, Karma und Communitys, in denen es aktiv ist.'],
  'App at dev.twitch.tv/console. Profile, description, creation date, channel type.': ['App su dev.twitch.tv/console. Profilo, descrizione, data di creazione, tipo di canale.', 'App en dev.twitch.tv/console. Perfil, descripción, fecha de creación, tipo de canal.', 'App unter dev.twitch.tv/console. Profil, Beschreibung, Erstellungsdatum, Kanaltyp.'],
  'Google Cloud API key (YouTube Data API v3, free quota). Channel by handle: country, description, creation date.': ['Chiave API di Google Cloud (YouTube Data API v3, quota gratuita). Canale per handle: paese, descrizione, data di creazione.', 'Clave API de Google Cloud (YouTube Data API v3, cuota gratuita). Canal por handle: país, descripción, fecha de creación.', 'Google-Cloud-API-Schlüssel (YouTube Data API v3, kostenloses Kontingent). Kanal per Handle: Land, Beschreibung, Erstellungsdatum.'],
  'api key': ['chiave API', 'clave API', 'API-Schlüssel'],
  'App at developer.spotify.com. Public profile of a user by id.': ['App su developer.spotify.com. Profilo pubblico di un utente per id.', 'App en developer.spotify.com. Perfil público de un usuario por id.', 'App unter developer.spotify.com. Öffentliches Profil eines Nutzers per ID.'],
  'API v2 bearer token (requires a paid plan). Profile, bio, location, website, creation date.': ['Bearer token dell\'API v2 (richiede un piano a pagamento). Profilo, bio, luogo, sito, data di creazione.', 'Bearer token de la API v2 (requiere un plan de pago). Perfil, biografía, ubicación, sitio, fecha de creación.', 'Bearer-Token der API v2 (erfordert einen kostenpflichtigen Tarif). Profil, Bio, Ort, Website, Erstellungsdatum.'],
  'Sources with a key': ['Fonti con chiave', 'Fuentes con clave', 'Quellen mit Schlüssel'],
  'Subdomains, historical resolutions and reputation of domains and IPs (free plan).': ['Sottodomini, risoluzioni storiche e reputazione di domini e IP (piano gratuito).', 'Subdominios, resoluciones históricas y reputación de dominios e IP (plan gratuito).', 'Subdomains, historische Auflösungen und Reputation von Domains und IPs (kostenloser Tarif).'],
  'Ports, banners and vulnerabilities of IPs, beyond the free InternetDB data.': ['Porte, banner e vulnerabilità degli IP oltre ai dati gratuiti di InternetDB.', 'Puertos, banners y vulnerabilidades de las IP, además de los datos gratuitos de InternetDB.', 'Ports, Banner und Schwachstellen von IPs zusätzlich zu den kostenlosen InternetDB-Daten.'],
  'Emails and address format of a domain.': ['Email e formato degli indirizzi di un dominio.', 'Correos y formato de las direcciones de un dominio.', 'E-Mails und Adressformat einer Domain.'],
  'Breaches with date and type of data exposed for each email.': ['Breach con data e tipo di dati esposti per ogni email.', 'Brechas con fecha y tipo de datos expuestos para cada correo.', 'Datenlecks mit Datum und Art der offengelegten Daten für jede E-Mail.'],
  'Subdomain list.': ['Elenco sottodomini.', 'Lista de subdominios.', 'Subdomain-Liste.'],
  'Reputation and reports of an IP.': ['Reputazione e segnalazioni di un IP.', 'Reputación y denuncias de una IP.', 'Reputation und Meldungen zu einer IP.'],
  'Tells whether an IP does mass scanning or is a known, benign service.': ['Dice se un IP fa scansioni di massa o è un servizio noto e benigno.', 'Indica si una IP hace escaneos masivos o es un servicio conocido e inofensivo.', 'Zeigt, ob eine IP Massenscans durchführt oder ein bekannter, harmloser Dienst ist.'],
  'Historical passive DNS of domains and IPs (free account).': ['DNS passivo storico di domini e IP (account gratuito).', 'DNS pasivo histórico de dominios e IP (cuenta gratuita).', 'Historisches passives DNS von Domains und IPs (kostenloses Konto).'],
  'Malicious URLs linked to a domain or IP (free account).': ['URL malevoli associati a un dominio o IP (account gratuito).', 'URL maliciosas asociadas a un dominio o IP (cuenta gratuita).', 'Bösartige URLs zu einer Domain oder IP (kostenloses Konto).'],
  'Companies and directors from the UK business register (free key).': ['Società e amministratori del registro imprese britannico (chiave gratuita).', 'Empresas y administradores del registro mercantil británico (clave gratuita).', 'Unternehmen und Geschäftsführer aus dem britischen Handelsregister (kostenloser Schlüssel).'],
  'key': ['chiave', 'clave', 'Schlüssel'],
  '<path>/backend': ['<percorso>/backend', '<ruta>/backend', '<Pfad>/backend'],
  'Built-in AI connector': ['Connettore AI integrato', 'Conector de IA integrado', 'Integrierter KI-Anbieter'],
  'The investigation graph (entities, relations, links) is sent to the chosen provider for summaries, checks and suggestions. With a local model (for example Ollama) the data does not leave your computer.': ['Il grafo dell\'indagine (entità, relazioni, collegamenti) viene inviato al provider scelto per riassunti, verifiche e suggerimenti. Con un modello locale (per esempio Ollama) i dati non lasciano il computer.', 'El grafo de la investigación (entidades, relaciones, enlaces) se envía al proveedor elegido para resúmenes, verificaciones y sugerencias. Con un modelo local (por ejemplo Ollama) los datos no salen del ordenador.', 'Der Untersuchungsgraph (Entitäten, Beziehungen, Verknüpfungen) wird für Zusammenfassungen, Prüfungen und Vorschläge an den gewählten Anbieter gesendet. Mit einem lokalen Modell (z. B. Ollama) verlassen die Daten den Computer nicht.'],
  'Provider': ['Provider', 'Proveedor', 'Anbieter'],
  'OpenAI-compatible (OpenAI, Ollama, LM Studio, OpenRouter…)': ['Compatibile OpenAI (OpenAI, Ollama, LM Studio, OpenRouter…)', 'Compatible con OpenAI (OpenAI, Ollama, LM Studio, OpenRouter…)', 'OpenAI-kompatibel (OpenAI, Ollama, LM Studio, OpenRouter…)'],
  'Model': ['Modello', 'Modelo', 'Modell'],
  'For example claude-sonnet-5-5.': ['Per esempio claude-sonnet-5-5.', 'Por ejemplo claude-sonnet-5-5.', 'Zum Beispiel claude-sonnet-5-5.'],
  'For example gpt-4o-mini or llama3.1.': ['Per esempio gpt-4o-mini o llama3.1.', 'Por ejemplo gpt-4o-mini o llama3.1.', 'Zum Beispiel gpt-4o-mini oder llama3.1.'],
  'Service address': ['Indirizzo del servizio', 'Dirección del servicio', 'Dienstadresse'],
  'Leave empty for the Anthropic service.': ['Lascia vuoto per il servizio Anthropic.', 'Déjalo vacío para el servicio de Anthropic.', 'Leer lassen für den Anthropic-Dienst.'],
  'Empty = OpenAI. For Ollama: http://localhost:11434/v1': ['Vuoto = OpenAI. Per Ollama: http://localhost:11434/v1', 'Vacío = OpenAI. Para Ollama: http://localhost:11434/v1', 'Leer = OpenAI. Für Ollama: http://localhost:11434/v1'],
  'optional': ['facoltativo', 'opcional', 'optional'],
  'API key': ['Chiave API', 'Clave API', 'API-Schlüssel'],
  'With a local service it can stay empty.': ['Con un servizio locale può restare vuota.', 'Con un servicio local puede quedar vacía.', 'Bei einem lokalen Dienst kann er leer bleiben.'],
  'Required for Anthropic.': ['Obbligatoria per Anthropic.', 'Obligatoria para Anthropic.', 'Für Anthropic erforderlich.'],
  'TEST THE CONNECTION': ['PROVA LA CONNESSIONE', 'PROBAR LA CONEXIÓN', 'VERBINDUNG TESTEN'],
  'Send my private notes': ['Invia le mie note private', 'Enviar mis notas privadas', 'Meine privaten Notizen senden'],
  'The notes and stars you put on nodes are included in the context.': ['Le note e le stelle che hai messo ai nodi vengono incluse nel contesto.', 'Las notas y estrellas que has puesto en los nodos se incluyen en el contexto.', 'Die Notizen und Sterne, die du an Knoten gesetzt hast, werden in den Kontext aufgenommen.'],
  'Maximum entities sent': ['Entità massime inviate', 'Máximo de entidades enviadas', 'Maximal gesendete Entitäten'],
  'Beyond this number the graph is reduced to the most connected (and favourite) ones.': ['Il grafo viene ridotto alle più collegate (e ai preferiti) oltre questo numero.', 'Al superar este número, el grafo se reduce a las más conectadas (y a las favoritas).', 'Über dieser Zahl wird der Graph auf die am stärksten verbundenen (und die favorisierten) reduziert.'],
  'MCP connector (for Claude Desktop and other agents)': ['Connettore MCP (per Claude Desktop e altri agenti)', 'Conector MCP (para Claude Desktop y otros agentes)', 'MCP-Anbindung (für Claude Desktop und andere Agenten)'],
  'Lets an AI assistant start and read OSINT-Fire investigations while the app is open. Add this block to your client\'s MCP configuration.': ['Permette a un assistente AI di avviare e leggere le indagini di OSINT-Fire mentre l\'app è aperta. Aggiungi questo blocco alla configurazione MCP del tuo client.', 'Permite a un asistente de IA iniciar y leer las investigaciones de OSINT-Fire mientras la app está abierta. Añade este bloque a la configuración MCP de tu cliente.', 'Erlaubt einem KI-Assistenten, OSINT-Fire-Untersuchungen zu starten und zu lesen, solange die App geöffnet ist. Füge diesen Block zur MCP-Konfiguration deines Clients hinzu.'],
  'Copy configuration': ['Copia configurazione', 'Copiar configuración', 'Konfiguration kopieren'],
  'MCP configuration copied': ['Configurazione MCP copiata', 'Configuración MCP copiada', 'MCP-Konfiguration kopiert'],
  'Local storage': ['Archivio locale', 'Almacén local', 'Lokaler Speicher'],
  'Path': ['Percorso', 'Ruta', 'Pfad'],
  'Size': ['Dimensione', 'Tamaño', 'Größe'],
  'Searches': ['Ricerche', 'Búsquedas', 'Suchen'],
  'Entities': ['Entità', 'Entidades', 'Entitäten'],
  'Evidence': ['Evidenze', 'Evidencias', 'Belege'],
  'Cached results': ['Risultati in cache', 'Resultados en caché', 'Ergebnisse im Cache'],
  'Images': ['Immagini', 'Imágenes', 'Bilder'],
  'Notes': ['Note', 'Notas', 'Notizen'],
  'Maintenance': ['Manutenzione', 'Mantenimiento', 'Wartung'],
  'Clear the cache': ['Svuota la cache', 'Vaciar la caché', 'Cache leeren'],
  'Deletes reusable results: the next search repeats all requests.': ['Cancella i risultati riusabili: la prossima ricerca rifà tutte le richieste.', 'Borra los resultados reutilizables: la próxima búsqueda repite todas las solicitudes.', 'Löscht wiederverwendbare Ergebnisse: Die nächste Suche wiederholt alle Anfragen.'],
  'CLEAR': ['SVUOTA', 'VACIAR', 'LEEREN'],
  'Cache cleared ({0} entries)': ['Cache svuotata ({0} voci)', 'Caché vaciada ({0} entradas)', 'Cache geleert ({0} Einträge)'],
  'Compact the database': ['Compatta il database', 'Compactar la base de datos', 'Datenbank komprimieren'],
  'Frees the space left by deleted data.': ['Libera lo spazio lasciato dai dati cancellati.', 'Libera el espacio que dejan los datos borrados.', 'Gibt den von gelöschten Daten belegten Platz frei.'],
  'COMPACT': ['COMPATTA', 'COMPACTAR', 'KOMPRIMIEREN'],
  'Database compacted': ['Database compattato', 'Base de datos compactada', 'Datenbank komprimiert'],
  'Full backup': ['Backup completo', 'Copia de seguridad completa', 'Vollständiges Backup'],
  'Saves a copy of searches, notes and settings (including API keys) to Downloads.': ['Salva in Download una copia di ricerche, note e impostazioni (comprese le chiavi API).', 'Guarda en Descargas una copia de búsquedas, notas y ajustes (incluidas las claves API).', 'Speichert eine Kopie von Suchen, Notizen und Einstellungen (einschließlich der API-Schlüssel) im Download-Ordner.'],
  'SAVE COPY': ['SALVA COPIA', 'GUARDAR COPIA', 'KOPIE SPEICHERN'],
  'Backup saved: {0}': ['Backup salvato: {0}', 'Copia guardada: {0}', 'Backup gespeichert: {0}'],
  'Danger zone': ['Zona pericolosa', 'Zona peligrosa', 'Gefahrenbereich'],
  'Delete all searches': ['Elimina tutte le ricerche', 'Eliminar todas las búsquedas', 'Alle Suchen löschen'],
  'Deletes searches, graphs, evidence, notes, images and cache. Settings are kept. This cannot be undone.': ['Cancella ricerche, grafi, evidenze, note, immagini e cache. Le impostazioni restano. Non si può annullare.', 'Borra búsquedas, grafos, evidencias, notas, imágenes y caché. Los ajustes se conservan. No se puede deshacer.', 'Löscht Suchen, Graphen, Belege, Notizen, Bilder und Cache. Die Einstellungen bleiben erhalten. Das lässt sich nicht rückgängig machen.'],
  'type {0} to confirm': ['scrivi {0} per confermare', 'escribe {0} para confirmar', 'zur Bestätigung {0} eingeben'],
  'Deleted {0} searches': ['Eliminate {0} ricerche', 'Eliminadas {0} búsquedas', '{0} Suchen gelöscht'],
  'DELETE EVERYTHING': ['ELIMINA TUTTO', 'ELIMINAR TODO', 'ALLES LÖSCHEN'],
};
